# NYF EDA

In [1]:
import numpy as np
import pandas as pd
import pandas_profiling as pp
import seaborn as sns
import bokeh as bkh
import matplotlib.pyplot as plt
from bokeh.io import output_file, show,output_notebook
from bokeh.palettes import Category20c
from bokeh.plotting import figure
from math import pi
from bokeh.transform import cumsum
output_file("carrier_pie.html")
output_notebook()

In [2]:
NYF_data=pd.read_csv('Dataset/NYF_data_no_NA.csv',parse_dates=['Travel_Date'])

In [3]:
NYF_data.corr()

,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,flight,air_time,distance,hour,minute,Month,Year
dep_time,1.000000,0.955672,0.258211,0.666349,0.787167,0.230353,0.049802,-0.019911,-0.019486,0.954351,0.091514,-0.005011,NaN
sched_dep_time,0.955672,1.000000,0.197427,0.648713,0.783342,0.172597,0.036495,-0.020519,-0.017995,0.999148,0.082960,-0.004573,NaN
dep_delay,0.258211,0.197427,1.000000,0.030099,0.159595,0.909897,0.056388,-0.022734,-0.022127,0.196747,0.028754,-0.019951,NaN
arr_time,0.666349,0.648713,0.030099,1.000000,0.793796,0.025285,0.033669,0.048636,0.041616,0.648656,0.041843,-0.003724,NaN
sched_arr_time,0.787167,0.783342,0.159595,0.793796,1.000000,0.132430,0.021594,0.073960,0.068726,0.783283,0.050321,-0.004173,NaN
arr_delay,0.230353,0.172597,0.909897,0.025285,0.132430,1.000000,0.074921,-0.036476,-0.062805,0.172148,0.021607,-0.017347,NaN
flight,0.049802,0.036495,0.056388,0.033669,0.021594,0.074921,1.000000,-0.475263,-0.484165,0.035838,0.018137,-0.000834,NaN
air_time,-0.019911,-0.020519,-0.022734,0.048636,0.073960,-0.036476,-0.475263,1.000000,0.990088,-0.021333,0.018375,0.012359,NaN
distance,-0.019486,-0.017995,-0.022127,0.041616,0.068726,-0.062805,-0.484165,0.990088,1.000000,-0.018860,0.019780,0.021636,NaN
hour,0.954351,0.999148,0.196747,0.648656,0.783283,0.172148,0.035838,-0.021333,-0.018860,1.000000,0.041768,-0.005227,NaN
minute,0.091514,0.082960,0.028754,0.041843,0.050321,0.021607,0.018137,0.018375,0.019780,0.041768,1.000000,0.015528,NaN
Month,-0.005011,-0.004573,-0.019951,-0.003724,-0.004173,-0.017347,-0.000834,0.012359,0.021636,-0.005227,0.015528,1.000000,NaN
Year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
NYF_data.head()

,Travel_Date,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,origin,dest,air_time,distance,hour,minute,time_hour,Month,Year,DayofWeek
0,2013-01-01,517,515,2,830,819,11,UA,1545,EWR,IAH,227.0,1400,5,15,01-01-2013 05:00,1,2013,Tuesday
1,2013-01-01,533,529,4,850,830,20,UA,1714,LGA,IAH,227.0,1416,5,29,01-01-2013 05:00,1,2013,Tuesday
2,2013-01-01,542,540,2,923,850,33,AA,1141,JFK,MIA,160.0,1089,5,40,01-01-2013 05:00,1,2013,Tuesday
3,2013-01-01,544,545,-1,1004,1022,-18,B6,725,JFK,BQN,183.0,1576,5,45,01-01-2013 05:00,1,2013,Tuesday
4,2013-01-01,554,600,-6,812,837,-25,DL,461,LGA,ATL,116.0,762,6,0,01-01-2013 06:00,1,2013,Tuesday

In [5]:
NYF_data.describe()

,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,flight,air_time,distance,hour,minute,Month,Year
count,336776.000000,336776.000000,336776.000000,336776.000000,336776.000000,336776.000000,336776.000000,336776.000000,336776.000000,336776.000000,336776.000000,336776.000000,336776.0
mean,1353.207963,1344.254840,12.681417,1506.733318,1536.380220,6.967138,1971.923620,149.648750,1039.912604,13.180247,26.230100,6.548510,2013.0
std,488.006603,467.335756,39.729587,532.350762,497.457142,44.024668,1632.471938,93.399588,733.233033,4.661316,19.300846,3.414457,0.0
min,1.000000,106.000000,-43.000000,1.000000,1.000000,-86.000000,1.000000,20.000000,17.000000,1.000000,0.000000,1.000000,2013.0
25%,910.000000,906.000000,-5.000000,1107.000000,1124.000000,-16.000000,553.000000,82.000000,502.000000,9.000000,8.000000,4.000000,2013.0
50%,1407.000000,1359.000000,-1.000000,1541.000000,1556.000000,-4.000000,1496.000000,128.000000,872.000000,13.000000,29.000000,7.000000,2013.0
75%,1747.000000,1729.000000,12.000000,1943.000000,1945.000000,14.000000,3465.000000,190.000000,1389.000000,17.000000,44.000000,10.000000,2013.0
max,2413.000000,2359.000000,1301.000000,2417.000000,2359.000000,1272.000000,8500.000000,1506.733318,4983.000000,23.000000,59.000000,12.000000,2013.0

In [6]:
report = pp.ProfileReport(NYF_data[['Travel_Date','carrier','origin','dest','dep_time','dep_delay','arr_time','arr_delay','air_time','flight','distance','Month','DayofWeek']])
report.to_file("NYF_Stats.html")

# Which carrier has most flight delay in minutes

In [7]:
bycarrierdept=NYF_data.groupby('carrier',as_index=False)

In [8]:
Dep_dly_mean=bycarrierdept['dep_delay'].mean()

In [9]:
Carriers=NYF_data.carrier.unique()

In [10]:
ax=sns.barplot(Carriers,Dep_dly_mean['dep_delay'],color='#FF6347',data=Dep_dly_mean)
ax.set(xlabel='Carrier', ylabel='Departure Delay in Min')
plt.show()

# Which Month is the most busiest month and highest delay

In [11]:
Months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sept','Oct','Nov','Dec']
weeks=['Mon','Tues','Web','Thur','Fri','Sat','Sun']

In [12]:
bymonth=NYF_data.groupby('Month',as_index=False)

In [13]:
byweek=NYF_data.groupby('DayofWeek',as_index=False)

In [14]:
Busiest_mnt=bymonth['flight'].mean()

In [15]:
Busiest_day=byweek['flight'].sum()

In [16]:
ax=sns.barplot(Months,Busiest_mnt['flight'],color='green',data=Busiest_mnt)
ax.set(xlabel='Month', ylabel='Number of flight')
plt.show()

In [17]:
ax=sns.barplot(weeks,Busiest_day['flight'],color='green',data=Busiest_day)
ax.set(xlabel='Week Day', ylabel='Number of flight')
plt.show()

In [18]:
Busiest_day

   DayofWeek     flight
0     Friday  100247140
1     Monday  101250430
2   Saturday   71006261
3     Sunday   90518821
4   Thursday   99990143
5    Tuesday  100755391
6  Wednesday  100328363

In [19]:
Highest_delay=bymonth['dep_delay'].mean()

In [20]:
ax=sns.barplot(Months,Highest_delay['dep_delay'],color='teal',data=Highest_delay)
ax.set(xlabel='Month', ylabel='Departure Delay in Min')
plt.show()

In [21]:
carrier_grp = NYF_data.groupby(['carrier']).count()

In [22]:
Carriers_operation=pd.Series(carrier_grp['origin']).reset_index(name='Flight_Nos')
Carriers_operation

   carrier  Flight_Nos
0       9E       18460
1       AA       32729
2       AS         714
3       B6       54635
4       DL       48110
5       EV       54173
6       F9         685
7       FL        3260
8       HA         342
9       MQ       26397
10      OO          32
11      UA       58665
12      US       20536
13      VX        5162
14      WN       12275
15      YV         601

In [23]:
Carriers_operation['angle'] = Carriers_operation['Flight_Nos']/Carriers_operation['Flight_Nos'].sum() * 2*pi
Carriers_operation['color'] = Category20c[len(Carriers_operation)]

In [24]:
Carriers_operation

   carrier  Flight_Nos     angle    color
0       9E       18460  0.344406  #3182bd
1       AA       32729  0.610621  #6baed6
2       AS         714  0.013321  #9ecae1
3       B6       54635  1.019318  #c6dbef
4       DL       48110  0.897582  #e6550d
5       EV       54173  1.010698  #fd8d3c
6       F9         685  0.012780  #fdae6b
7       FL        3260  0.060821  #fdd0a2
8       HA         342  0.006381  #31a354
9       MQ       26397  0.492485  #74c476
10      OO          32  0.000597  #a1d99b
11      UA       58665  1.094505  #c7e9c0
12      US       20536  0.383137  #756bb1
13      VX        5162  0.096307  #9e9ac8
14      WN       12275  0.229013  #bcbddc
15      YV         601  0.011213  #dadaeb

In [25]:
p = figure(plot_height=350, title="Most number of flight with respect to carrier", toolbar_location=None, tools="hover", x_range=(-0.5, 1.0))

In [26]:
p.wedge(x=0, y=1, radius=0.4,
        start_angle=cumsum('angle', include_zero=True), end_angle=cumsum('angle'),
        line_color="white", fill_color='color', legend='carrier', source=Carriers_operation)

p.axis.axis_label=None
p.axis.visible=False
p.grid.grid_line_color = None

In [27]:
show(p);

In [28]:
flight=NYF_data[['carrier','origin','flight']]

In [29]:
flight=pd.pivot_table(flight,index=['carrier'],values='flight',columns='origin',aggfunc=np.sum)
flight

origin           EWR         JFK         LGA
carrier
9E         4749476.0  51542354.0   9556055.0
AA         4740278.0  10432486.0  14806094.0
AS            8706.0         NaN         NaN
B6         5906285.0  26288946.0   4474028.0
DL         5325558.0  23164383.0  37651577.0
EV       195816198.0   8044064.0  46640137.0
F9               NaN         NaN    469385.0
FL               NaN         NaN   1651670.0
HA               NaN     17442.0         NaN
MQ         8304404.0  26321367.0  67135635.0
OO           27164.0         NaN    147099.0
UA        47422502.0   2487457.0   6379132.0
US         4654023.0   2819693.0  25995193.0
VX          276138.0    861214.0         NaN
WN         9572812.0         NaN   8434609.0
YV               NaN         NaN   1972985.0

In [30]:
#fligh=fligh.dropna(how='any',axis=0)
flight=flight.fillna(0)
flight

origin           EWR         JFK         LGA
carrier
9E         4749476.0  51542354.0   9556055.0
AA         4740278.0  10432486.0  14806094.0
AS            8706.0         0.0         0.0
B6         5906285.0  26288946.0   4474028.0
DL         5325558.0  23164383.0  37651577.0
EV       195816198.0   8044064.0  46640137.0
F9               0.0         0.0    469385.0
FL               0.0         0.0   1651670.0
HA               0.0     17442.0         0.0
MQ         8304404.0  26321367.0  67135635.0
OO           27164.0         0.0    147099.0
UA        47422502.0   2487457.0   6379132.0
US         4654023.0   2819693.0  25995193.0
VX          276138.0    861214.0         0.0
WN         9572812.0         0.0   8434609.0
YV               0.0         0.0   1972985.0

In [31]:
pal = sns.dark_palette("palegreen", as_cmap=True)

In [32]:
ax = sns.heatmap(flight, cmap=pal)

In [33]:
plt.figure()
sns.pairplot(data=NYF_data[["carrier","origin","flight","arr_delay","dep_delay"]],
             hue="carrier", dropna=True)
plt.savefig("carrier_pair_plot.png")

![](carrier_pair_plot.png)

In [34]:
plt.show();

In [35]:
plt.figure()
sns.pairplot(data=NYF_data[["DayofWeek","flight","arr_delay","dep_delay"]],
             hue="DayofWeek", dropna=True)
plt.savefig("DayofWeek_pair_plot.png")

![](DayofWeek_pair_plot.png)

In [36]:
plt.show()